// Builds every static SVG in assets/ and writes README.md.  Run: node scripts/build.mjs
// Stats are separate (scripts/stats.mjs) because they need the GitHub API and refresh daily.
import { themes, write } from "./lib.mjs";
import { hero } from "./hero.mjs";
import {
  button,
  certCard,
  certHeight,
  currently,
  experienceSvg,
  footerSvg,
  journeySvg,
  papersSvg,
  sectionHead,
  tile,
  toolboxSvg,
  workCard,
} from "./sections.mjs";
import { SITE, certifications, journey, profile, projects } from "./data.mjs";

const out = [];
const both = (name, make) => {
  for (const t of Object.values(themes)) out.push(write(`assets/${name}-${t.name}.svg`, make(t)));
};

out.push(write("assets/hero.svg", hero()));

const buttons = [
  { id: "portfolio", label: "Portfolio", iconName: "globe", href: SITE, primary: true },
  { id: "resume", label: "Resume", iconName: "file", href: profile.resume },
  { id: "linkedin", label: "LinkedIn", iconName: "linkedin", href: profile.linkedin },
  { id: "email", label: profile.email, iconName: "mail", href: `mailto:${profile.email}` },
];
for (const b of buttons) out.push(write(`assets/button-${b.id}.svg`, button(b)));

const heads = {
  work: { eyebrow: "Selected work", title: "Seven systems, each with a write-up of what worked and what didn't" },
  journey: { eyebrow: "Journey so far", title: "Every layer trained on the one before it" },
  trail: { eyebrow: "Experience, research and recognition", title: "The paper trail" },
  activity: { eyebrow: "GitHub activity", title: "The commits behind the case studies" },
};
for (const [id, h] of Object.entries(heads)) both(`head-${id}`, (t) => sectionHead(t, h));

both("currently", currently);

// Cards in a row share one body height so they line up side by side.
const rows = [projects.slice(0, 2), projects.slice(2, 4), projects.slice(4, 7)];
for (const row of rows) {
  for (const t of Object.values(themes)) {
    const h = Math.max(...row.map((p) => workCard(t, p).bodyH));
    for (const p of row) out.push(write(`assets/work-${p.slug}-${t.name}.svg`, workCard(t, p, h).svg));
  }
}

const tiles = [
  { id: "resume", iconName: "file", title: "Resume", sub: "One page, PDF", href: profile.resume },
  { id: "portfolio", iconName: "globe", title: "Portfolio", sub: "Full case studies, live", href: SITE },
  { id: "papers", iconName: "book", title: "3 papers", sub: "Presented 2024 – 2026", href: `${SITE}/#research` },
];
for (const tl of tiles) both(`tile-${tl.id}`, (t) => tile(t, tl));

both("journey", journeySvg);
both("experience", experienceSvg);
both("papers", papersSvg);
both("toolbox", toolboxSvg);
for (const t of Object.values(themes)) {
  const h = certHeight(t);
  for (const c of certifications) out.push(write(`assets/cert-${c.id}-${t.name}.svg`, certCard(t, c, h)));
}
out.push(write("assets/footer.svg", footerSvg()));

/* ---------- README ---------- */
const pic = (name, alt, attrs = 'width="100%"') =>
  `<picture><source media="(prefers-color-scheme: dark)" srcset="assets/${name}-dark.svg"><img src="assets/${name}-light.svg" alt="${alt}" ${attrs}></picture>`;
const link = (href, inner) => `<a href="${href}">${inner}</a>`;
const milestones = journey.reduce((n, y) => n + y.milestones.length, 0);
const buttonRow = buttons.map((b) => link(b.href, `<img src="assets/button-${b.id}.svg" alt="${b.label}" height="44">`)).join("\n");
const cardRow = (row, width) => row.map((p) => link(`${SITE}/work/${p.slug}`, pic(`work-${p.slug}`, `${p.title}: ${p.hook}`, `width="${width}"`))).join("\n");

const readme = `<!-- Generated by scripts/build.mjs from scripts/data.mjs. Edit those, then run: node scripts/build.mjs -->

${link(SITE, `<img src="assets/hero.svg" alt="${profile.name}, ${profile.title}. Building AI that shows its work. ${profile.summary}" width="100%">`)}

<p>
${buttonRow}
</p>

<br>

${pic("currently", "Currently: I'm finishing my B.Tech at GIET and building Q-CONSENSUS, where five AI agents debate, a QAOA optimizer picks the consensus, and every step is anchored on a blockchain. This summer I was a generative AI intern at CTTC, Ministry of MSME.")}

<br><br>

${link(`${SITE}/#work`, pic("head-work", `${heads.work.eyebrow}: ${heads.work.title}`))}

<p>
${cardRow(rows[0], "49.6%")}
</p>
<p>
${cardRow(rows[1], "49.6%")}
</p>
<p>
${cardRow(rows[2], "32.9%")}
</p>
<p>
${tiles.map((tl) => link(tl.href, pic(`tile-${tl.id}`, `${tl.title}: ${tl.sub}`, 'width="32.9%"'))).join("\n")}
</p>

<br>

${link(`${SITE}/#journey`, pic("head-journey", `${heads.journey.eyebrow}: ${heads.journey.title}`))}

<details>
<summary><b>From a hardware paper to multi-agent systems in three years</b> · show all ${milestones} milestones</summary>
<br>

${pic("journey", "Timeline of milestones from 2024 to 2027")}

</details>

<br><br>

${link(`${SITE}/#research`, pic("head-trail", `${heads.trail.eyebrow}: ${heads.trail.title}`))}

${pic("experience", "Experience: Generative AI Intern at CTTC, Ministry of MSME; Data Science Trainee & Intern at Jyesta Corporate Entity × E-Cell IIT Roorkee; Backend Engineering Trainee at Boot.dev. Education: B.Tech CSE at GIET Bhubaneswar, CGPA 8.8.")}

<br>

${pic("papers", "Three publications (2024–2026) and awards: 1st place Model Fiesta, 3rd place ReFlow Hackathon, Quantum Computing merit certificate")}

<p>
${certifications.map((c) => link(c.href, pic(`cert-${c.id}`, `${c.name}, ${c.issuer}`, 'width="24.5%"'))).join("\n")}
</p>

<br>

${pic("toolbox", "How I work: explainable models, local LLMs, quantum judged against classical, verifiable records, hardware in the loop, and shipping with Docker")}

<br><br>

${pic("head-activity", `${heads.activity.eyebrow}: ${heads.activity.title}`)}

${pic("stats", "GitHub activity: contributions, streaks, contribution calendar and languages, refreshed daily")}

<br><br>

<img src="assets/footer.svg" alt="Contact: curious about intelligence, serious about shipping it. ${profile.availability}, ${profile.location}." width="100%">

<p>
${buttonRow}
</p>
`;
out.push(write("README.md", readme));

const kb = out.reduce((s, f) => s + f.bytes, 0) / 1024;
console.log(`${out.length} files, ${kb.toFixed(0)} KB total`);
for (const f of out.filter((f) => f.bytes > 120_000)) console.log(`  large: ${f.rel} ${(f.bytes / 1024).toFixed(0)} KB`);
